version: 1.0
image: Visual Studio 2019

environment:
  matrix:
    - PYTHON: "C:\\Python38"

before_build:
  - set PATH=C:\Python38;%PATH%
  - python -m pip install --upgrade pip
  - pip install -r requirements.txt

build_script:
  - python -m pytest

test: off